<a href="https://colab.research.google.com/github/Colsai/DATA690_MATH_ML/blob/main/Week1_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Numpy as NP
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(a, axis = 0)

#Adds the cols

array([5, 7, 9])

In [7]:
a = np.array([[-5, 7, 9], [10, 11, 0], [1, -1, 2]])
b = np.array([1,1,1]).T

In [9]:
#a dot b
a.dot(b)

array([11, 21,  2])

In [11]:
np.array([1,1,1]).T == np.array([[1],[1],[1]])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])